repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        name: ruff-sort-imports
        args: [--select, I, --fix]
      - id: ruff
        name: ruff-linter
        args: [--fix]
      - id: ruff-format
        name: ruff-formatter
